name: Deploy Kutt Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: terraform apply -var-file=dev.tfvars -auto-approve

    - name: Capture Private Key
      id: capture_private_key
      run: |
        PRIVATE_KEY=$(terraform output -raw private_key_pem)
        echo "$PRIVATE_KEY" > private_key.pem
        cat private_key.pem # Debug step to ensure private key is captured correctly
      shell: bash

    - name: Get Public IP
      id: get_ip
      run: |
        PUBLIC_IP=$(terraform output -raw public_ip)
        echo "::set-output name=public_ip::$PUBLIC_IP"
      shell: bash

    - name: Add private key to SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ steps.get_ip.outputs.public_ip }} << 'EOF'
          cd /app_docker_storage/kutt
          git pull
          docker-compose up -d --build
        EOF
      shell: bash
